stages:
  - mavenbuild
  - maventest
  - mavendeploy
  - androidbuild
  - androidtest

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

maven-build:
  stage: mavenbuild
  tags:
    - springboot_tag
  script:
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
    - export PATH=$JAVA_HOME/bin:$PATH
    - cd Backend
    - mvn package
  artifacts:
    paths:
      - Backend/target/*.jar
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - Backend/**/*
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Backend/**/*

maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
    - export PATH=$JAVA_HOME/bin:$PATH
    - cd Backend
    - mvn test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - Backend/**/*
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Backend/**/*

auto-deploy:
  stage: mavendeploy
  tags:
    - springboot_tag
  script:
    - cd Backend
    - sudo mv target/*.jar /target/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
  rules:
    - if: $CI_COMMIT_BRANCH == "main"  # Only deploy on main branch
      changes:
        - Backend/**/*

android-build:
  image: afirefly/android-ci:java17
  stage: androidbuild
  tags:
    - android_tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend
    - ./gradlew build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - Frontend/**/*
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Frontend/**/*

android-test:
  image: afirefly/android-ci:java17
  stage: androidtest
  tags:
    - android_tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend
    - ./gradlew test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - Frontend/**/*
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Frontend/**/*
